CREATE DATABASE DISAFRA_APP;
USE DISAFRA_APP;

-- ------------------- TABLAS ------------------------ --
CREATE TABLE IF NOT EXISTS SUCURSAL(
	CODIGO VARCHAR(12) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PERMISO(
	ID_PERMISO INT NOT NULL,
    PERMISO VARCHAR(20) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS USUARIO(
	US VARCHAR(15) NOT NULL,
    PSW VARCHAR(64) NOT NULL,
    SUCURSAL VARCHAR(12) NULL,
    ACTIVO TINYINT(1) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DETALLE_PERMISO(
	ID_DETALLE INT NOT NULL,
    US VARCHAR(15) NULL,
    PERMISO INT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PROVEEDOR(
	ID_PROVEEDOR INT NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CLIENTE(
	NIT VARCHAR(12) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DIRECCION_CLIENTE(
	ID_DIRECCION INT NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    NIT_CLIENTE VARCHAR(12) NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TELEFONO_CLIENTE(
	NUMERO VARCHAR(15) NOT NULL,
    NIT_CLIENTE VARCHAR(12) NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS EMPLEADO(
	CODIGO INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    DPI VARCHAR(12) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    COD_SUCURSAL VARCHAR(12) NULL,
    JEFE_INMEDIATO INT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PUESTO_EMPLEADO(
	ID_PUESTO INT NOT NULL,
    NOMBRE VARCHAR(45) NOT NULL,
    SALARIO DOUBLE(6,2) NULL,
    HORARIO_ENTRADA TIME NULL,
    HORARIO_SALIDA TIME NULL,
    REQUISITOS VARCHAR(255) NULL,
    COD_EMPLEADO INT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TELEFONO_EMPLEADO(
	NUMERO VARCHAR(15) NOT NULL,
    CONTACTO_EMERGENCIA TINYINT(1) NULL,
    COD_EMPLEADO INT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS VENTA(
	NUM_VENTA INT NOT NULL,
    HORA_EMISION TIME NOT NULL,
    FECHA_EMISION DATE NOT NULL,
    NIT_CLIENTE VARCHAR(12) NULL,
    COD_EMPLEADO INT NULL,
    COD_SUCURSAL VARCHAR(12) NULL,
    TOTAL DOUBLE(8,2) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS COMPRA(
	NUM_COMPRA INT NOT NULL,
    HORA_COMPRA TIME NULL,
    FECHA_COMPRA DATE NULL,
    COD_EMPLEADO INT NULL,
    PROVEEDOR INT NULL,
    TOTAL DOUBLE(8,2) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	CODIGO INT NOT NULL,
    NOMBRE VARCHAR(35) NOT NULL,
    CATEGORIA INT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PRODUCTO(
	CODIGO VARCHAR(18) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    PRECIO_COSTO DOUBLE(6,2) NOT NULL,
    PORCENTAJE_GANANCIA DOUBLE(3,2) NOT NULL,
    PRECIO_VENTA DOUBLE(8,2) NOT NULL,
    COD_CATEGORIA INT NULL,
    COD_SUCURSAL VARCHAR(12) NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DETALLE_VENTA(
	ID_DETALLE INT NOT NULL,
    NUM_VENTA INT NULL,
    COD_PRODUCTO VARCHAR(18) NULL,
    CANTIDAD INT NOT NULL,
    SUBTOTAL DOUBLE(8,2) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DETALLE_COMPRA(
	ID_DETALLE INT NOT NULL,
    NUM_COMPRA INT NULL,
    COD_PRODUCTO VARCHAR(18) NULL,
    CANTIDAD INT NOT NULL,
    SUBTOTAL DOUBLE(8,2) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TIPO_TRANSACCION(
	ID_TRANSACCION INT NOT NULL,
    NOMBRE VARCHAR(8) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TRANSACCION(
	NUM_TRANSACCION INT NOT NULL,
    HORA_TRANSACCION TIME NULL,
    FECHA_TRANSACCION DATE NULL,
    COD_EMPLEADO INT NULL,
    SUCURSAL_ENVIA VARCHAR(12) NULL,
    SUCURSAL_RECIBE VARCHAR(12) NULL,
    ID_TIPO INT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DETALLE_TRANSACCION(
	ID_DETALLE INT NOT NULL,
    COD_PRODUCTO VARCHAR(18) NULL,
    CANTIDAD INT NOT NULL,
    NUM_TRANSACCION INT NULL
)ENGINE=InnoDB;

-- ------------------------- PRIMARY KEY ------------------ --

ALTER TABLE SUCURSAL
ADD CONSTRAINT PK_SUCURSAL
PRIMARY KEY(CODIGO);

ALTER TABLE USUARIO
ADD CONSTRAINT PK_USUARIO
PRIMARY KEY(US);

ALTER TABLE PERMISO
ADD CONSTRAINT PK_PERMISO
PRIMARY KEY(ID_PERMISO);

ALTER TABLE DETALLE_PERMISO
ADD CONSTRAINT PK_DETALLE_PERMISO
PRIMARY KEY(ID_DETALLE);

ALTER TABLE PROVEEDOR
ADD CONSTRAINT PK_PROVEEDOR
PRIMARY KEY(ID_PROVEEDOR);

ALTER TABLE CLIENTE
ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY(NIT);

ALTER TABLE DIRECCION_CLIENTE
ADD CONSTRAINT PK_DIRECCION_CLIENTE
PRIMARY KEY(ID_DIRECCION);

ALTER TABLE TELEFONO_CLIENTE
ADD CONSTRAINT PK_TELEFONO_CLIENTE
PRIMARY KEY(NUMERO);

ALTER TABLE EMPLEADO
ADD CONSTRAINT PK_EMPLEADO
PRIMARY KEY(CODIGO);

ALTER TABLE PUESTO_EMPLEADO
ADD CONSTRAINT PK_PUESTO_EMPLEADO
PRIMARY KEY(ID_PUESTO);

ALTER TABLE TELEFONO_EMPLEADO
ADD CONSTRAINT PK_TELEFONO_EMPLEADO
PRIMARY KEY(NUMERO);

ALTER TABLE VENTA
ADD CONSTRAINT PK_VENTA
PRIMARY KEY(NUM_VENTA);

ALTER TABLE COMPRA
ADD CONSTRAINT PK_COMPRA
PRIMARY KEY(NUM_COMPRA);

ALTER TABLE CATEGORIA
ADD CONSTRAINT PK_CATEGORIA
PRIMARY KEY(CODIGO);

ALTER TABLE PRODUCTO
ADD CONSTRAINT PK_PRODUCTO
PRIMARY KEY(CODIGO);

ALTER TABLE DETALLE_VENTA
ADD CONSTRAINT PK_DETALLE_VENTA
PRIMARY KEY(ID_DETALLE);

ALTER TABLE DETALLE_COMPRA
ADD CONSTRAINT PK_DETALLE_COMPRA
PRIMARY KEY(ID_DETALLE);

ALTER TABLE TIPO_TRANSACCION
ADD CONSTRAINT PK_TIPO_TRANSACCION
PRIMARY KEY(ID_TRANSACCION);

ALTER TABLE TRANSACCION
ADD CONSTRAINT PK_TRANSACCION
PRIMARY KEY(NUM_TRANSACCION);

ALTER TABLE DETALLE_TRANSACCION
ADD CONSTRAINT PK_DETALLE_TRANSACCION
PRIMARY KEY(ID_DETALLE);

-- ------------------ INCREMENTS ------------------- --

ALTER TABLE PROVEEDOR MODIFY ID_PROVEEDOR INT AUTO_INCREMENT;
ALTER TABLE DIRECCION_CLIENTE MODIFY ID_DIRECCION INT AUTO_INCREMENT;
ALTER TABLE EMPLEADO MODIFY CODIGO INT AUTO_INCREMENT;
ALTER TABLE PUESTO_EMPLEADO MODIFY ID_PUESTO INT AUTO_INCREMENT;
ALTER TABLE VENTA MODIFY NUM_VENTA INT AUTO_INCREMENT;
ALTER TABLE COMPRA MODIFY NUM_COMPRA INT AUTO_INCREMENT;
ALTER TABLE CATEGORIA MODIFY CODIGO INT AUTO_INCREMENT;
ALTER TABLE DETALLE_COMPRA MODIFY ID_DETALLE INT AUTO_INCREMENT;
ALTER TABLE DETALLE_VENTA MODIFY ID_DETALLE INT AUTO_INCREMENT;
ALTER TABLE TIPO_TRANSACCION MODIFY ID_TRANSACCION INT AUTO_INCREMENT;
ALTER TABLE TRANSACCION MODIFY NUM_TRANSACCION INT AUTO_INCREMENT;
ALTER TABLE DETALLE_TRANSACCION MODIFY ID_DETALLE INT AUTO_INCREMENT;
ALTER TABLE PERMISO MODIFY ID_PERMISO INT AUTO_INCREMENT;
ALTER TABLE DETALLE_PERMISO MODIFY ID_DETALLE INT AUTO_INCREMENT;

-- ------------------FOREIGN KEY ------------------- --

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_SUCURSAL
FOREIGN KEY(SUCURSAL) REFERENCES SUCURSAL(CODIGO)
ON DELETE SET NULL;

ALTER TABLE DETALLE_PERMISO
ADD CONSTRAINT FK_DETALLEPERMISO_USUARIO
FOREIGN KEY(US) REFERENCES USUARIO(US)
ON DELETE SET NULL;

ALTER TABLE DETALLE_PERMISO
ADD CONSTRAINT FK_DETALLEPERMISO_PERMISO
FOREIGN KEY(PERMISO) REFERENCES PERMISO(ID_PERMISO)
ON DELETE SET NULL;

ALTER TABLE DIRECCION_CLIENTE
ADD CONSTRAINT FK_DIRECCIONCLIENTE_CLIENTE
FOREIGN KEY(NIT_CLIENTE) REFERENCES CLIENTE(NIT)
ON DELETE SET NULL;

ALTER TABLE TELEFONO_CLIENTE
ADD CONSTRAINT FK_TELEFONOCLIENTE_CLIENTE
FOREIGN KEY(NIT_CLIENTE) REFERENCES CLIENTE(NIT)
ON DELETE SET NULL;

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_EMPLEADO
FOREIGN KEY(JEFE_INMEDIATO) REFERENCES EMPLEADO(CODIGO)
ON DELETE SET NULL;

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_SUCURSAL
FOREIGN KEY(COD_SUCURSAL) REFERENCES SUCURSAL(CODIGO)
ON DELETE SET NULL;

ALTER TABLE PUESTO_EMPLEADO
ADD CONSTRAINT FK_PUESTOEMPLEADO_EMPLEADO
FOREIGN KEY(COD_EMPLEADO) REFERENCES EMPLEADO(CODIGO)
ON DELETE SET NULL;

ALTER TABLE TELEFONO_EMPLEADO
ADD CONSTRAINT FK_TELEFONOEMPLEADO_EMPLEADO
FOREIGN KEY(COD_EMPLEADO) REFERENCES EMPLEADO(CODIGO)
ON DELETE SET NULL;

ALTER TABLE VENTA
ADD CONSTRAINT FK_VENTA_CLIENTE
FOREIGN KEY(NIT_CLIENTE) REFERENCES CLIENTE(NIT)
ON DELETE SET NULL;

ALTER TABLE VENTA
ADD CONSTRAINT FK_VENTA_EMPLEADO
FOREIGN KEY(COD_EMPLEADO) REFERENCES EMPLEADO(CODIGO)
ON DELETE SET NULL;

ALTER TABLE VENTA
ADD CONSTRAINT FK_VENTA_SUCURSAL
FOREIGN KEY(COD_SUCURSAL) REFERENCES SUCURSAL(CODIGO)
ON DELETE SET NULL;

ALTER TABLE COMPRA
ADD CONSTRAINT FK_COMPRA_EMPLEADO
FOREIGN KEY(COD_EMPLEADO) REFERENCES EMPLEADO(CODIGO)
ON DELETE SET NULL;

ALTER TABLE COMPRA
ADD CONSTRAINT FK_COMPRA_PROVEEDOR
FOREIGN KEY(PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR)
ON DELETE SET NULL;

ALTER TABLE CATEGORIA
ADD CONSTRAINT FK_CATEGORIA_CATEGORIA
FOREIGN KEY(CATEGORIA) REFERENCES CATEGORIA(CODIGO)
ON DELETE SET NULL;

ALTER TABLE PRODUCTO
ADD CONSTRAINT FK_PRODUCTO_CATEGORIA
FOREIGN KEY(COD_CATEGORIA) REFERENCES CATEGORIA(CODIGO)
ON DELETE SET NULL;

ALTER TABLE PRODUCTO
ADD CONSTRAINT FK_PRODUCTO_SUCURSAL
FOREIGN KEY(COD_SUCURSAL) REFERENCES SUCURSAL(CODIGO)
ON DELETE SET NULL;

ALTER TABLE DETALLE_VENTA
ADD CONSTRAINT FK_DETALLEVENTA_VENTA
FOREIGN KEY(NUM_VENTA) REFERENCES VENTA(NUM_VENTA)
ON DELETE SET NULL;

ALTER TABLE DETALLE_VENTA
ADD CONSTRAINT FK_DETALLEVENTA_PRODUCTO
FOREIGN KEY(COD_PRODUCTO) REFERENCES PRODUCTO(CODIGO)
ON DELETE SET NULL;

ALTER TABLE DETALLE_COMPRA
ADD CONSTRAINT FK_DETALLECOMPRA_COMPRA
FOREIGN KEY(NUM_COMPRA) REFERENCES COMPRA(NUM_COMPRA)
ON DELETE SET NULL;

ALTER TABLE DETALLE_COMPRA
ADD CONSTRAINT FK_DETALLECOMPRA_PRODUCTO
FOREIGN KEY(COD_PRODUCTO) REFERENCES PRODUCTO(CODIGO)
ON DELETE SET NULL;

ALTER TABLE TRANSACCION
ADD CONSTRAINT FK_TRANSACCION_EMPLEADO
FOREIGN KEY(COD_EMPLEADO) REFERENCES EMPLEADO(CODIGO)
ON DELETE SET NULL;

ALTER TABLE TRANSACCION
ADD CONSTRAINT FK_TRANSACCION_SUCURSAL1
FOREIGN KEY(SUCURSAL_ENVIA) REFERENCES SUCURSAL(CODIGO)
ON DELETE SET NULL;

ALTER TABLE TRANSACCION
ADD CONSTRAINT FK_TRANSACCION_SUCURSAL2
FOREIGN KEY(SUCURSAL_RECIBE) REFERENCES SUCURSAL(CODIGO)
ON DELETE SET NULL;

ALTER TABLE TRANSACCION
ADD CONSTRAINT FK_TRANSACCION_TIPO
FOREIGN KEY(ID_TIPO) REFERENCES TIPO_TRANSACCION(ID_TRANSACCION)
ON DELETE SET NULL;

ALTER TABLE DETALLE_TRANSACCION
ADD CONSTRAINT FK_DETALLETRANSACCION_PRODUCTO
FOREIGN KEY(COD_PRODUCTO) REFERENCES PRODUCTO(CODIGO)
ON DELETE SET NULL;

ALTER TABLE DETALLE_TRANSACCION
ADD CONSTRAINT FK_DETALLETRANSACCION_TRANSACCION
FOREIGN KEY(NUM_TRANSACCION) REFERENCES TRANSACCION(NUM_TRANSACCION)
ON DELETE SET NULL;